import sharp from "sharp";
import JSZip from "jszip";
import pngToIco from "png-to-ico";

export interface FaviconPackage {
  zipBuffer: Buffer;
  previews: Record<string, string>; // base64 strings for preview grid
}

interface FaviconPackageNaming {
  folderName: string;
  zipFilename: string;
}

function sanitizeBaseName(filename: string): string {
  const withoutExtension = filename.replace(/\.[^.]+$/, "").trim();

  const sanitized = withoutExtension
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, "-")
    .replace(/\s+/g, " ")
    .replace(/\.+$/g, "")
    .trim();

  return sanitized || "favicon";
}

export function buildFaviconPackageNaming(filename: string): FaviconPackageNaming {
  const baseName = sanitizeBaseName(filename);

  return {
    folderName: `${baseName}-favicon-pack`,
    zipFilename: `${baseName}-favicon-pack.zip`,
  };
}

export async function generateFaviconPackage(
  inputBuffer: Buffer,
  folderName = "favicon-pack"
): Promise<FaviconPackage> {
  // First, we create a high quality square base image
  const baseImage = sharp(inputBuffer)
    .resize(512, 512, {
      fit: 'contain', // ensure entire logo fits
      background: { r: 255, g: 255, b: 255, alpha: 0 } // preserve transparency
    });

  const baseBuffer = await baseImage.png().toBuffer();

  const sizes = [16, 32, 48, 64, 96, 180, 192, 512];
  const sizeBuffers: Record<number, Buffer> = {};
  const previews: Record<string, string> = {};

  for (const size of sizes) {
    const resized = await sharp(baseBuffer).resize(size, size).png().toBuffer();
    sizeBuffers[size] = resized;
    // We also provide base64 for the UI previews (only small ones to save RAM)
    if (size <= 192) {
      previews[`${size}x${size}`] = `data:image/png;base64,${resized.toString('base64')}`;
    }
  }

  // Generate the .ico file
  // pngToIco expects either a file path or a buffer, or array of buffers.
  // It handles multiple resolutions nicely.
  const icoBuffer = await pngToIco([sizeBuffers[16], sizeBuffers[32], sizeBuffers[48]]);

  // Build the ZIP file
  const zip = new JSZip();
  const folder = zip.folder(folderName) || zip;

  folder.file("favicon.ico", icoBuffer);
  folder.file("favicon-16x16.png", sizeBuffers[16]);
  folder.file("favicon-32x32.png", sizeBuffers[32]);
  folder.file("favicon-48x48.png", sizeBuffers[48]);
  folder.file("favicon-64x64.png", sizeBuffers[64]);
  folder.file("favicon-96x96.png", sizeBuffers[96]);
  folder.file("apple-touch-icon.png", sizeBuffers[180]);
  folder.file("android-chrome-192x192.png", sizeBuffers[192]);
  folder.file("android-chrome-512x512.png", sizeBuffers[512]);

  // Create site.webmanifest
  const webmanifest = {
    name: "My Application",
    short_name: "App",
    icons: [
      {
        src: "/android-chrome-192x192.png",
        sizes: "192x192",
        type: "image/png"
      },
      {
        src: "/android-chrome-512x512.png",
        sizes: "512x512",
        type: "image/png"
      }
    ],
    theme_color: "#ffffff",
    background_color: "#ffffff",
    display: "standalone"
  };

  folder.file("site.webmanifest", JSON.stringify(webmanifest, null, 2));

  // Instructions
  const instructions = `Favicon Package generated by ImageForge

To use this package:
1. Extract all files to the root directory of your website (e.g. your 'public' folder)
2. Add the following tags to your HTML <head>:

<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
  `;
  folder.file("favicon-instructions.txt", instructions);

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

  return {
    zipBuffer,
    previews
  };
}
